### ISSUE TITLE
PHP Fatal error:  require(): Failed opening required '.../kbjr/Git.php/Git.php' 

### ISSUE THREAD

**Issue by COLABORATI** [boonebgorges/wp-cli-git-helper#7]
PHP Fatal error:  require(): Failed opening required '.../boonebgorges/wp-cli-git-helper/vendor/kbjr/Git.php/Git.php'

**Comment by boonebgorges** [comment]
I've reworked the command so that the required library is pulled in via composer. Reclone this repo, and then run `composer install`.

@danielbachhuber Can I bother you for a moment with a stupid question? What should package authors do to ensure that `wp package install` contains a built version of our command? Should I be preparing specific Github Releases? Or does wp-cli build for me? (Is that what's happening when `wp package install` calls `\Composer\Installer\setUpdate()`?)

**Comment by danielbachhuber** [comment]
> What should package authors do to ensure that `wp package install` contains a built version of our command?

There's no "built version", per se. Under the hood, `wp package install` modifies the user's `composer.json` listing all of their packages to include this new package, and then runs the equivalent of `composer install`. As long as your WP-CLI package has a valid `composer.json` with its dependencies, they'll be installed on installation.

**Comment by boonebgorges** [comment]
@danielbachhuber Perfect - thanks!

**Comment by boonebgorges** [comment]
No longer using this library, and I've also switched to a proper Composer build process.
